# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 669)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.input2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.input2.setFont(font)
        self.input2.setText("")
        self.input2.setAlignment(QtCore.Qt.AlignCenter)
        self.input2.setObjectName("input2")
        self.gridLayout.addWidget(self.input2, 2, 0, 1, 2)
        self.input1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.input1.setFont(font)
        self.input1.setText("")
        self.input1.setAlignment(QtCore.Qt.AlignCenter)
        self.input1.setObjectName("input1")
        self.gridLayout.addWidget(self.input1, 1, 0, 1, 2)
        self.bu_kommen = QtWidgets.QPushButton(self.centralwidget)
        self.bu_kommen.setIconSize(QtCore.QSize(50, 50))
        self.bu_kommen.setDefault(True)
        self.bu_kommen.setFlat(False)
        self.bu_kommen.setObjectName("bu_kommen")
        self.gridLayout.addWidget(self.bu_kommen, 0, 0, 1, 1)
        self.bu_gehen = QtWidgets.QPushButton(self.centralwidget)
        self.bu_gehen.setIconSize(QtCore.QSize(50, 50))
        self.bu_gehen.setDefault(True)
        self.bu_gehen.setObjectName("bu_gehen")
        self.gridLayout.addWidget(self.bu_gehen, 0, 1, 1, 1)
        self.bu_reg = QtWidgets.QPushButton(self.centralwidget)
        self.bu_reg.setDefault(True)
        self.bu_reg.setObjectName("bu_reg")
        self.gridLayout.addWidget(self.bu_reg, 4, 0, 1, 2)
        self.daten = QtWidgets.QFormLayout()
        self.daten.setObjectName("daten")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.daten.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.daten.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.daten.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.daten.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.daten.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.gridLayout.addLayout(self.daten, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bu_kommen.setText(_translate("MainWindow", "Kommen"))
        self.bu_gehen.setText(_translate("MainWindow", "Gehen"))
        self.bu_reg.setText(_translate("MainWindow", "Registrierung"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Nachname:"))
